<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>LiraSlabZones.Core</RootNamespace>
    <AssemblyName>LiraSlabZones.Core</AssemblyName>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AppendPlatformToOutputPath>true</AppendPlatformToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="LiraSapr.Interop">
      <HintPath>..\..\interop\LiraSapr.Interop.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>true</Private>
    </Reference>
    <Reference Include="LiraResAPI.Interop">
      <HintPath>..\..\interop\LiraResAPI.Interop.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
